import {CreateUserDto} from '../models/create-user.dto';

export const initialUsers: CreateUserDto[] = [
  { name: 'Madilyn Day', active: true },
  { name: 'Kayson Marin', active: true },
  { name: 'Celia Poole', active: true },
  { name: 'Quincy Keith', active: true },
  { name: 'Elyse McCullough', active: true },
  { name: 'Briar Fuller', active: true },
  { name: 'Oakley Jordan', active: true },
  { name: 'Sawyer Church', active: true },
  { name: 'Ayleen Stout', active: true },
  { name: 'Callahan Quintana', active: true },
  { name: 'Kenia Turner', active: true },
  { name: 'Joshua Pace', active: true },
  { name: 'Giana Yang', active: true },
  { name: 'Malcolm Case', active: true },
  { name: 'Cleo Barr', active: true },
  { name: 'Harley Rowland', active: true },
  { name: 'Harleigh Stafford', active: true },
  { name: 'Alfredo Alfaro', active: true },
  { name: 'Yasmin Horton', active: true },
  { name: 'Garrett Galindo', active: true },
  { name: 'Corinne Fuentes', active: true },
  { name: 'Bowen Alvarez', active: true },
  { name: 'Leilani Skinner', active: true },
  { name: 'Ridge Dominguez', active: true },
]
